package pkgEnum;

public enum GameState {
	START, INPROGRESS, FINISHED, BONUS, WS_COLLECTTUTORIAL, WS_COLLECTTUTORIAL1, WS_COLLECT, WS_PHTUTORIAL, WS_PH, WS_TEMP, 
	BONUS_WRONG, BONUS_RIGHT, TUTORIAL, TRANSITION1, TRANSITION2, TUTORIAL2;
}

//test
//yet another test
