package pkgEnum;

import java.io.Serializable;

public enum GameState implements Serializable{

	START, INPROGRESS, FINISHED, BONUS, WS_COLLECTTUTORIAL, WS_COLLECT, WS_PHTUTORIAL, WS_PH, WS_TEMP, 
	BONUS_WRONG, BONUS_RIGHT, TUTORIAL, SC_TUTORIAL_FOOD, SC_TUTORIAL_TRASH, SC_TUTORIAL_SEAWEED, SC_TUTORIAL_BREATH,
  TRANSITION1, TRANSITION2, TUTORIAL2;

}
